import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.*;
import java.util.*;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Jan 20, 2014, 9:16:11 PM
 */

/**
 *
 * @author vikas
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Itempurchase = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        Confirmpurchase = new javax.swing.JButton();
        OptionsDialog = new javax.swing.JDialog();
        CrRAButton = new javax.swing.JRadioButton();
        ElRAButton = new javax.swing.JRadioButton();
        GaRAButton = new javax.swing.JRadioButton();
        SpRAButton = new javax.swing.JRadioButton();
        FuRAButton = new javax.swing.JRadioButton();
        VeRAButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        CrockeriesDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        CT = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ct1 = new javax.swing.JTextField();
        ct2 = new javax.swing.JTextField();
        CB2 = new javax.swing.JButton();
        CB1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ElectronicsDialog = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        ET = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        et1 = new javax.swing.JTextField();
        et2 = new javax.swing.JTextField();
        EB1 = new javax.swing.JButton();
        EB2 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        FurnituresDialog = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        FT = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ft1 = new javax.swing.JTextField();
        ft2 = new javax.swing.JTextField();
        FB1 = new javax.swing.JButton();
        FB2 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        SportsDialog = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        ST = new javax.swing.JTable();
        st1 = new javax.swing.JTextField();
        st2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        SB1 = new javax.swing.JButton();
        SB2 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        GarmentsDialog = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        GT = new javax.swing.JTable();
        gt1 = new javax.swing.JTextField();
        gt2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GB1 = new javax.swing.JButton();
        GB2 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        VegetablesDialog = new javax.swing.JDialog();
        jScrollPane7 = new javax.swing.JScrollPane();
        VT = new javax.swing.JTable();
        vt1 = new javax.swing.JTextField();
        vt2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        VB1 = new javax.swing.JButton();
        VB2 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        TransactionDialog = new javax.swing.JDialog();
        jScrollPane8 = new javax.swing.JScrollPane();
        cm = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ENTERname = new javax.swing.JTextField();
        ID = new javax.swing.JLabel();
        TransactionID = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();

        Itempurchase.setMinimumSize(new java.awt.Dimension(800, 600));
        Itempurchase.getContentPane().setLayout(null);

        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Itemcode", "Item Name", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ItemTable);

        Itempurchase.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(170, 70, 452, 180);

        Confirmpurchase.setText("Confirm Purchase");
        Confirmpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmpurchaseActionPerformed(evt);
            }
        });
        Itempurchase.getContentPane().add(Confirmpurchase);
        Confirmpurchase.setBounds(280, 350, 190, 60);

        OptionsDialog.setMinimumSize(new java.awt.Dimension(1000, 680));
        OptionsDialog.getContentPane().setLayout(null);

        CrRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/CROCKERY-large.jpg"))); // NOI18N
        CrRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(CrRAButton);
        CrRAButton.setBounds(50, 70, 340, 80);

        ElRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/imagesCAC54QMB - Copy.jpg"))); // NOI18N
        ElRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(ElRAButton);
        ElRAButton.setBounds(50, 220, 350, 80);

        GaRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/O2_Garments_Logo_20130131134932 - Copy.jpg"))); // NOI18N
        GaRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(GaRAButton);
        GaRAButton.setBounds(590, 230, 340, 70);

        SpRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/sports_lan1.jpg"))); // NOI18N
        SpRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(SpRAButton);
        SpRAButton.setBounds(670, 60, 190, 100);

        FuRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/imagesCAN2OQKI - Copy.jpg"))); // NOI18N
        FuRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FuRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(FuRAButton);
        FuRAButton.setBounds(50, 380, 360, 80);

        VeRAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/2221cd36ad1b605c5239a649fc5ca92b - Copy.png"))); // NOI18N
        VeRAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeRAButtonActionPerformed(evt);
            }
        });
        OptionsDialog.getContentPane().add(VeRAButton);
        VeRAButton.setBounds(600, 370, 330, 90);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/3d_colorful_squares-wide.jpg"))); // NOI18N
        OptionsDialog.getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1110, 650);

        CrockeriesDialog.setMinimumSize(new java.awt.Dimension(900, 700));
        CrockeriesDialog.getContentPane().setLayout(null);

        CT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CT);

        CrockeriesDialog.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 210, 560, 120);

        jLabel5.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel5.setText("Enter Product no. to purchase");
        CrockeriesDialog.getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 370, 240, 30);

        jLabel6.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel6.setText("Quantity");
        CrockeriesDialog.getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 430, 100, 19);

        ct1.setText("ICC");
        CrockeriesDialog.getContentPane().add(ct1);
        ct1.setBounds(550, 370, 110, 30);
        CrockeriesDialog.getContentPane().add(ct2);
        ct2.setBounds(550, 430, 110, 30);

        CB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        CB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB2ActionPerformed(evt);
            }
        });
        CrockeriesDialog.getContentPane().add(CB2);
        CB2.setBounds(250, 510, 170, 70);

        CB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        CB1.setText("Purchase");
        CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB1ActionPerformed(evt);
            }
        });
        CrockeriesDialog.getContentPane().add(CB1);
        CB1.setBounds(500, 510, 200, 70);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Logo3.jpg"))); // NOI18N
        CrockeriesDialog.getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 10, 800, 120);

        jLabel21.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel21.setText("Please Choose Your Product");
        CrockeriesDialog.getContentPane().add(jLabel21);
        jLabel21.setBounds(350, 170, 320, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/croc.JPG"))); // NOI18N
        CrockeriesDialog.getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 920, 630);

        ElectronicsDialog.setMinimumSize(new java.awt.Dimension(1080, 680));
        ElectronicsDialog.getContentPane().setLayout(null);

        ET.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of Item", "Price", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ET);

        ElectronicsDialog.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 120, 510, 140);

        jLabel7.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Enter Product no. to purchase");
        ElectronicsDialog.getContentPane().add(jLabel7);
        jLabel7.setBounds(510, 290, 230, 30);

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Quantity");
        ElectronicsDialog.getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 370, 100, 20);

        et1.setText("ICE");
        ElectronicsDialog.getContentPane().add(et1);
        et1.setBounds(830, 290, 170, 40);
        ElectronicsDialog.getContentPane().add(et2);
        et2.setBounds(830, 360, 170, 30);

        EB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        EB1.setText("Purchase");
        EB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EB1ActionPerformed(evt);
            }
        });
        ElectronicsDialog.getContentPane().add(EB1);
        EB1.setBounds(810, 521, 180, 69);

        EB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        EB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EB2ActionPerformed(evt);
            }
        });
        ElectronicsDialog.getContentPane().add(EB2);
        EB2.setBounds(510, 520, 180, 70);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel22.setText("Electronics Market");
        ElectronicsDialog.getContentPane().add(jLabel22);
        jLabel22.setBounds(360, 20, 390, 60);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/LG_MC3087AUPGBDRQEIL_sbig - Copy.jpg"))); // NOI18N
        ElectronicsDialog.getContentPane().add(jLabel23);
        jLabel23.setBounds(20, 360, 440, 250);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Grids_Grid_File24_1384577994040 - Copy.jpg"))); // NOI18N
        ElectronicsDialog.getContentPane().add(jLabel24);
        jLabel24.setBounds(20, 110, 444, 250);

        jLabel26.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel26.setText("Please Choose Your Product");
        ElectronicsDialog.getContentPane().add(jLabel26);
        jLabel26.setBounds(630, 80, 340, 40);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/electronics.jpg"))); // NOI18N
        ElectronicsDialog.getContentPane().add(jLabel25);
        jLabel25.setBounds(10, 0, 1050, 640);

        FurnituresDialog.setMinimumSize(new java.awt.Dimension(1020, 700));
        FurnituresDialog.getContentPane().setLayout(null);

        FT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of Item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(FT);

        FurnituresDialog.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(502, 190, 490, 130);

        jLabel9.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel9.setText("Enter Product no. to purchase");
        FurnituresDialog.getContentPane().add(jLabel9);
        jLabel9.setBounds(560, 350, 230, 19);

        jLabel10.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel10.setText("Quantity");
        FurnituresDialog.getContentPane().add(jLabel10);
        jLabel10.setBounds(640, 400, 80, 19);

        ft1.setText("ICF");
        FurnituresDialog.getContentPane().add(ft1);
        ft1.setBounds(850, 340, 120, 30);
        FurnituresDialog.getContentPane().add(ft2);
        ft2.setBounds(860, 400, 120, 30);

        FB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        FB1.setText("Purchase");
        FB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FB1ActionPerformed(evt);
            }
        });
        FurnituresDialog.getContentPane().add(FB1);
        FB1.setBounds(790, 500, 190, 70);

        FB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        FB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FB2ActionPerformed(evt);
            }
        });
        FurnituresDialog.getContentPane().add(FB2);
        FB2.setBounds(540, 500, 180, 70);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/renowned-furniture-logo-design.jpg"))); // NOI18N
        FurnituresDialog.getContentPane().add(jLabel27);
        jLabel27.setBounds(70, 10, 820, 90);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/cardboard-furniture-design.jpg"))); // NOI18N
        FurnituresDialog.getContentPane().add(jLabel28);
        jLabel28.setBounds(30, 180, 470, 390);

        jLabel29.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel29.setText("Please Choose Your Product");
        FurnituresDialog.getContentPane().add(jLabel29);
        jLabel29.setBounds(570, 150, 310, 40);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/background%20with%20logo.jpg"))); // NOI18N
        FurnituresDialog.getContentPane().add(jLabel30);
        jLabel30.setBounds(0, 0, 1010, 660);

        SportsDialog.setMinimumSize(new java.awt.Dimension(1080, 680));
        SportsDialog.getContentPane().setLayout(null);

        ST.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(ST);

        SportsDialog.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(510, 270, 520, 140);

        st1.setText("ICS");
        SportsDialog.getContentPane().add(st1);
        st1.setBounds(890, 420, 140, 30);
        SportsDialog.getContentPane().add(st2);
        st2.setBounds(890, 490, 140, 30);

        jLabel11.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jLabel11.setText("Enter Product no. to Purchase");
        SportsDialog.getContentPane().add(jLabel11);
        jLabel11.setBounds(550, 420, 280, 30);

        jLabel12.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        jLabel12.setText("Quantity");
        SportsDialog.getContentPane().add(jLabel12);
        jLabel12.setBounds(550, 480, 90, 20);

        SB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        SB1.setText("Purchase");
        SB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SB1ActionPerformed(evt);
            }
        });
        SportsDialog.getContentPane().add(SB1);
        SB1.setBounds(850, 560, 180, 69);

        SB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        SB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SB2ActionPerformed(evt);
            }
        });
        SportsDialog.getContentPane().add(SB2);
        SB2.setBounds(480, 560, 180, 70);

        jLabel31.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Please Choose Your Product");
        SportsDialog.getContentPane().add(jLabel31);
        jLabel31.setBounds(600, 230, 320, 50);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/logo_trssports.jpg"))); // NOI18N
        SportsDialog.getContentPane().add(jLabel32);
        jLabel32.setBounds(320, 10, 530, 190);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/sportsequipment - Copy.jpg"))); // NOI18N
        SportsDialog.getContentPane().add(jLabel33);
        jLabel33.setBounds(40, 250, 390, 290);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/sports.jpg"))); // NOI18N
        SportsDialog.getContentPane().add(jLabel34);
        jLabel34.setBounds(0, 0, 1110, 680);

        GarmentsDialog.setMinimumSize(new java.awt.Dimension(1000, 650));
        GarmentsDialog.getContentPane().setLayout(null);

        GT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of item", "Price", "Size"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(GT);

        GarmentsDialog.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(530, 160, 452, 130);

        gt1.setText("ICG");
        GarmentsDialog.getContentPane().add(gt1);
        gt1.setBounds(870, 340, 110, 40);
        GarmentsDialog.getContentPane().add(gt2);
        gt2.setBounds(870, 410, 110, 30);

        jLabel13.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 255, 255));
        jLabel13.setText("Enter Product no. to Purchase");
        GarmentsDialog.getContentPane().add(jLabel13);
        jLabel13.setBounds(560, 330, 230, 40);

        jLabel14.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 255, 255));
        jLabel14.setText("Quantity");
        GarmentsDialog.getContentPane().add(jLabel14);
        jLabel14.setBounds(580, 410, 90, 20);

        GB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        GB1.setText("Purchase");
        GB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GB1ActionPerformed(evt);
            }
        });
        GarmentsDialog.getContentPane().add(GB1);
        GB1.setBounds(810, 530, 190, 70);

        GB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        GB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GB2ActionPerformed(evt);
            }
        });
        GarmentsDialog.getContentPane().add(GB2);
        GB2.setBounds(510, 530, 180, 70);

        jLabel35.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 255, 255));
        jLabel35.setText("Please Choose Your Product");
        GarmentsDialog.getContentPane().add(jLabel35);
        jLabel35.setBounds(610, 100, 340, 50);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/engineered-garments-bedford-jacket_051308 - Copy.jpg"))); // NOI18N
        GarmentsDialog.getContentPane().add(jLabel36);
        jLabel36.setBounds(10, 110, 430, 520);

        jLabel37.setFont(new java.awt.Font("Forte", 1, 36)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 51));
        jLabel37.setText("Garments Market  ");
        GarmentsDialog.getContentPane().add(jLabel37);
        jLabel37.setBounds(420, 10, 330, 90);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/12967176-round-denim-background.jpg"))); // NOI18N
        GarmentsDialog.getContentPane().add(jLabel38);
        jLabel38.setBounds(0, 0, 1190, 840);

        VegetablesDialog.setMinimumSize(new java.awt.Dimension(1050, 650));
        VegetablesDialog.getContentPane().setLayout(null);

        VT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product no.", "Name of item", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(VT);

        VegetablesDialog.getContentPane().add(jScrollPane7);
        jScrollPane7.setBounds(250, 190, 452, 110);

        vt1.setText("ICV");
        VegetablesDialog.getContentPane().add(vt1);
        vt1.setBounds(550, 330, 140, 30);
        VegetablesDialog.getContentPane().add(vt2);
        vt2.setBounds(550, 380, 140, 30);

        jLabel15.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 102));
        jLabel15.setText("Enter Product no. to Purchase");
        VegetablesDialog.getContentPane().add(jLabel15);
        jLabel15.setBounds(240, 330, 260, 30);

        jLabel16.setFont(new java.awt.Font("Arial Unicode MS", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 204, 51));
        jLabel16.setText("Quantity");
        VegetablesDialog.getContentPane().add(jLabel16);
        jLabel16.setBounds(240, 380, 100, 20);

        VB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/h.png"))); // NOI18N
        VB1.setText("Purchase");
        VB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VB1ActionPerformed(evt);
            }
        });
        VegetablesDialog.getContentPane().add(VB1);
        VB1.setBounds(540, 470, 200, 70);

        VB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/untitled.png"))); // NOI18N
        VB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VB2ActionPerformed(evt);
            }
        });
        VegetablesDialog.getContentPane().add(VB2);
        VB2.setBounds(230, 470, 180, 70);

        jLabel39.setFont(new java.awt.Font("Forte", 1, 48)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 204, 51));
        jLabel39.setText("Vegetable Market");
        VegetablesDialog.getContentPane().add(jLabel39);
        jLabel39.setBounds(260, 30, 470, 90);

        jLabel46.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 204, 0));
        jLabel46.setText("Please Choose your Product");
        VegetablesDialog.getContentPane().add(jLabel46);
        jLabel46.setBounds(320, 160, 330, 30);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Supermarkt - Copy.jpg"))); // NOI18N
        VegetablesDialog.getContentPane().add(jLabel40);
        jLabel40.setBounds(0, 0, 990, 660);

        TransactionDialog.setMinimumSize(new java.awt.Dimension(800, 600));
        TransactionDialog.getContentPane().setLayout(null);

        cm.setColumns(20);
        cm.setRows(5);
        jScrollPane8.setViewportView(cm);

        TransactionDialog.getContentPane().add(jScrollPane8);
        jScrollPane8.setBounds(130, 190, 440, 250);

        jLabel17.setText("CASH-MEMO");
        TransactionDialog.getContentPane().add(jLabel17);
        jLabel17.setBounds(340, 120, 80, 60);

        jButton2.setText("Make Payment");
        TransactionDialog.getContentPane().add(jButton2);
        jButton2.setBounds(460, 490, 120, 40);

        jButton3.setText("Back");
        TransactionDialog.getContentPane().add(jButton3);
        jButton3.setBounds(170, 490, 130, 40);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/images (4).jpg"))); // NOI18N
        TransactionDialog.getContentPane().add(jLabel41);
        jLabel41.setBounds(130, 80, 110, 110);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/DSC_85631.jpg"))); // NOI18N
        TransactionDialog.getContentPane().add(jLabel42);
        jLabel42.setBounds(610, 260, 170, 120);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/RCO0018.JPG"))); // NOI18N
        TransactionDialog.getContentPane().add(jLabel43);
        jLabel43.setBounds(610, 80, 170, 160);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/k5035399.jpg"))); // NOI18N
        TransactionDialog.getContentPane().add(jLabel44);
        jLabel44.setBounds(610, 400, 170, 130);

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Fast%20Buying1 - Copy.jpg"))); // NOI18N
        TransactionDialog.getContentPane().add(jLabel45);
        jLabel45.setBounds(270, 0, 210, 140);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 800));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        jLabel1.setText("Please have your SHOPPING ID and Enjoy SHOPPIN!!!!!!");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 240, 610, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Enter Your Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 300, 160, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Your Shopping ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 350, 170, 20);

        ENTERname.setText("XYZ");
        getContentPane().add(ENTERname);
        ENTERname.setBounds(510, 300, 160, 30);
        getContentPane().add(ID);
        ID.setBounds(520, 330, 150, 20);

        TransactionID.setText("Generate Transaction  ID");
        TransactionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransactionIDActionPerformed(evt);
            }
        });
        getContentPane().add(TransactionID);
        TransactionID.setBounds(180, 440, 250, 70);

        jButton1.setText("Go SHOPPIN!!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(510, 440, 250, 70);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/ext.png"))); // NOI18N
        jButton4.setText("jButton4");
        getContentPane().add(jButton4);
        jButton4.setBounds(690, 520, 190, 170);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/New folder/Fast%20Buying1 - Copy - Copy.jpg"))); // NOI18N
        jLabel18.setMinimumSize(new java.awt.Dimension(1400, 1600));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(0, 0, 890, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents
Calendar p = Calendar.getInstance();
  		 int day = p.get(Calendar.DATE);
   		 int month = p.get(Calendar.MONTH) + 1;
   		 int year = p.get(Calendar.YEAR);
 int hour = p.get(Calendar.HOUR);
  		 int minute = p.get(Calendar.MINUTE);
   		 String z = day + "_" + month + "_" + year + "_" + hour + "_" + minute;

    private void TransactionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransactionIDActionPerformed

        String na = ENTERname.getText();
        String Ta = na + z;
        if (na.equals("XYZ")) {
            JOptionPane.showMessageDialog(null, "Please Enter Your Name to Generate Shopping ID");
        }
        else {
            String w = na + hour + ":" + minute + "  " + day + "/" + month + "/" + year;
            Itempurchase.setVisible(true);
            ID.setText("" + w);
        }

        try {
            Class.forName("java.sql.Driver");
            Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
            Statement s = d.createStatement();

            String q = "create table  " + Ta + " (Item_code varchar(25), Item_purchased varchar(40), Price float(10), Quantity float(10));";
            s.executeUpdate(q);
        }
             catch (Exception e) { System.out.println(e.getMessage());}


        // TODO add your handling code here:
    }//GEN-LAST:event_TransactionIDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
OptionsDialog.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CrRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrRAButtonActionPerformed
CrockeriesDialog.setVisible(true);

try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from crockery ";
            ResultSet rs = s.executeQuery(q);
 DefaultTableModel dtm = (DefaultTableModel) CT.getModel();
     while (rs.next()) {
                String n = rs.getString("CrocName");
                String k = rs.getString("ProducNo");
                int a = rs.getInt("Price");

                dtm.addRow(new Object[]{k, n, a});
                CrRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
       }
        // TODO add your handling code here:
    }//GEN-LAST:event_CrRAButtonActionPerformed

    private void CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB1ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from crockery ";
            ResultSet rs = s.executeQuery(q);

            int tpe = CT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = ct2.getText();
            String pe = ct1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);

            int pe3 = Integer.parseInt(j);
            if (ct1.getText().equals("ICC")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        ct1.setText("ICC");
                        ct2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProducNo");
                        String n = rs.getString("CrocName");
                        int a = rs.getInt("Price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});
                        ct1.setText("");
                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
                        Statement x = d.createStatement();
                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + ");";
                         x.executeUpdate(r);

                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CB1ActionPerformed

    private void CB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB2ActionPerformed
       DefaultTableModel dtm1 = (DefaultTableModel) CT.getModel();
        int row= dtm1.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm1.removeRow(0);
        CrockeriesDialog.dispose();
        CrRAButton.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_CB2ActionPerformed

    private void ElRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElRAButtonActionPerformed
        ElectronicsDialog.setVisible(true);
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from electronicitems ";
            ResultSet  rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) ET.getModel();
            while (rs.next()) {
                String n = rs.getString("Name");
                String k = rs.getString("ProductNo");
                int a = rs.getInt("Price");
                int b = rs.getInt("Size");
                dtm.addRow(new Object[]{k, n, a, b});
                ElRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ElRAButtonActionPerformed

    private void EB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EB2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) ET.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        ElectronicsDialog.dispose();
        ElRAButton.setSelected(false);

        // TODO add your handling code here:
}//GEN-LAST:event_EB2ActionPerformed

    private void EB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from electronicitems ";
            ResultSet rs = s.executeQuery(q);
            String na = ENTERname.getText();
            String Ta = na + z;
            int tpe = ET.getRowCount();
            String j = et2.getText();
            String pe = et1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);
            if (et1.getText().equals("ICE")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    }
                    if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        et1.setText("ICE");
                        et2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("Name");
                        int a = rs.getInt("Price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
                        Statement x = d.createStatement();
                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + ");";
                        x.executeUpdate(r);
                       }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_EB1ActionPerformed

    private void FuRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuRAButtonActionPerformed
          FurnituresDialog.setVisible(true);
            try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from furniture ";
            ResultSet rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) FT.getModel();
            while (rs.next()) {
                          String n = rs.getString("Name");
            String k = rs.getString("Productno");
            int a = rs.getInt("Price");


                dtm.addRow(new Object[]{k, n, a});
                FuRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_FuRAButtonActionPerformed

    private void FB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FB1ActionPerformed
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from furniture ";
            ResultSet rs = s.executeQuery(q);

            int tpe = FT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = ft2.getText();
            String pe = ft1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);
            if (ft1.getText().equals("ICF")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        ft1.setText("ICF");
                        ft2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("Name");
                        int a = rs.getInt("Price");

                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + "); ";
                       x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_FB1ActionPerformed

    private void FB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FB2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) FT.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        FurnituresDialog.dispose();
        FuRAButton.setSelected(false);

        // TODO add your handling code here:
}//GEN-LAST:event_FB2ActionPerformed

    private void SpRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpRAButtonActionPerformed
SportsDialog.setVisible(true);
        try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from sports ";
            ResultSet rs = s.executeQuery(q);

            DefaultTableModel dtm = (DefaultTableModel) ST.getModel();
            while (rs.next()) {
                String n = rs.getString("SportsItem");
                String k = rs.getString("Productno");
                int a = rs.getInt("price");

                dtm.addRow(new Object[]{k, n, a});
                SpRAButton.setSelected(false);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SpRAButtonActionPerformed

    private void SB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SB2ActionPerformed
          DefaultTableModel dtm = (DefaultTableModel) ST.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        SportsDialog.dispose();
        SpRAButton.setSelected(false);
     // TODO add your handling code here:
    }//GEN-LAST:event_SB2ActionPerformed

    private void SB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from sports ";
            ResultSet rs = s.executeQuery(q);
            String na = ENTERname.getText();
            String Ta = na + z;
            int tpe = ST.getRowCount();
            String j = st2.getText();
            String pe = st1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);

            if (st1.getText().equals("ICS")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        st1.setText("ICS");
                        st2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("SportsItem");
                        int a = rs.getInt("Price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + ");";
                        x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_SB1ActionPerformed

    private void GaRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaRAButtonActionPerformed
            GarmentsDialog.setVisible(true);
            try {
                Class.forName("java.sql.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
                Statement s = c.createStatement();
                String q = "select * from garments ";
                ResultSet rs = s.executeQuery(q);

                DefaultTableModel dtm2 = (DefaultTableModel) GT.getModel();
                while (rs.next()) {
                    String n = rs.getString("GarName");
                    String k = rs.getString("Productno");
                    int a = rs.getInt("Price");
                    int b = rs.getInt("Size");
                    dtm2.addRow(new Object[]{k, n, a, b});
                    GaRAButton.setSelected(false);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_GaRAButtonActionPerformed

    private void GB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from garments ";
            ResultSet rs = s.executeQuery(q);

            int tpe = GT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = gt2.getText();
            String pe = gt1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);

            if (gt1.getText().equals("ICG")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        gt1.setText("ICG");
                        gt2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("Productno");
                        String n = rs.getString("GarName");
                        int a = rs.getInt("Price");
                        dtm1.addRow(new Object[]{co, n, a, pe3});
                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values('" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + "); ";
                        x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_GB1ActionPerformed

    private void GB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GB2ActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) GT.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        GarmentsDialog.dispose();
        GaRAButton.setSelected(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_GB2ActionPerformed

    private void VeRAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeRAButtonActionPerformed
            VegetablesDialog.setVisible(true);
            try {
                Class.forName("java.sql.Driver");
                Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
                Statement s = c.createStatement();
                String q = "select * from vegetables ";
                ResultSet rs = s.executeQuery(q);

                DefaultTableModel dtm = (DefaultTableModel) VT.getModel();
                while (rs.next()) {
                    String n = rs.getString("VegName");
                    String k = rs.getString("ProductNo");
                    int a = rs.getInt("PricePerKg");

                    dtm.addRow(new Object[]{k, n, a});
                    VeRAButton.setSelected(false);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_VeRAButtonActionPerformed

    private void VB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VB1ActionPerformed
try {
            Class.forName("java.sql.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarketProject", "root", "abc123");
            Statement s = c.createStatement();
            String q = "select * from vegetables ";
            ResultSet rs = s.executeQuery(q);

            int tpe = VT.getRowCount();
            String na = ENTERname.getText();
            String Ta = na + z;
            String j = vt2.getText();
            String pe = vt1.getText();
            String pe1 = pe.substring(3);
            int pe2 = Integer.parseInt(pe1);
            int pe3 = Integer.parseInt(j);

            if (vt1.getText().equals("ICV")) {
                JOptionPane.showMessageDialog(null, "Please Enter The Product No. and Quantity you want to buy");
            } else {
                if (j.equals("0")) {
                    JOptionPane.showMessageDialog(null, "Please Enter The Quantity you want to buy");
                } else {
                    if (pe2 > tpe) {
                        JOptionPane.showMessageDialog(null, "There are only " + tpe + "Products in our Stock");
                    } else if (pe3 <= 0) {
                        JOptionPane.showMessageDialog(null, "Invalid Entry");
                    } else {
                        vt1.setText("ICV");
                        vt2.setText("0");
                        DefaultTableModel dtm1 = (DefaultTableModel) ItemTable.getModel();
                        rs.absolute(pe2);
                        String co = rs.getString("ProductNo");
                        String n = rs.getString("VegName");
                        int a = rs.getInt("PricePerKg");

                        dtm1.addRow(new Object[]{co, n, a, pe3});

                        Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
                        Statement x = d.createStatement();

                        String r = "Insert into  " + Ta + " values(" + "'" + co + "'" + "," + "'" + n + "'" + "," + "'" + a + "'" + "," + "'" + pe3 + "'" + "); ";
                        x.executeUpdate(r);
                    }
                }
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_VB1ActionPerformed

    private void VB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VB2ActionPerformed
         DefaultTableModel dtm = (DefaultTableModel) VT.getModel();
        int row= dtm.getRowCount();
        if(row>0)
            for(int i=0; i<row; i++)
                dtm.removeRow(0);
        VegetablesDialog.dispose();
        VeRAButton.setSelected(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_VB2ActionPerformed

    private void ConfirmpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmpurchaseActionPerformed
String na = ENTERname.getText();
        String Ta = na + z;
        String w = na + hour + ":" + minute + "  " + day + "/" + month + "/" + year;
        try {
                Class.forName("java.sql.Driver");
                Connection d = DriverManager.getConnection("jdbc:mysql://localhost:3306/SuperMarket_purchase", "root", "abc123");
                Statement s = d.createStatement();
                String q = "select * from " + Ta + ";";
                ResultSet rs = s.executeQuery(q);
                TransactionDialog.setVisible(true);
                cm.setText("");

                cm.append("            Customer Name  :-   " + na);
                cm.append("\n" + "            Customer ID :-   " + w);

                int c, e = 0;
                while (rs.next()) {
                    String g = rs.getString("Item_code");
                    String f = rs.getString("Item_purchased");
                    int a = rs.getInt("Price");
                    int b = rs.getInt("Quantity");
                    c = a * b;
                    e = e + c;
                    cm.append("\n" + "            " + g + "            " + f + " :  Rs.  " + a + " per unit   " + b + "  Units    Net : Rs.     " + c);
                }

                cm.append("\n");
                cm.append("\n");

                cm.append("\n" + "            " + "Total Amount to be paid :- Rs.  " + e);
                cm.append("\n");
                cm.append("\n" + "            Thank You For Shopping. Have a nice day ...      ");
              } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        // TODO add your handling code here:
    }//GEN-LAST:event_ConfirmpurchaseActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CB1;
    private javax.swing.JButton CB2;
    private javax.swing.JTable CT;
    private javax.swing.JButton Confirmpurchase;
    private javax.swing.JRadioButton CrRAButton;
    private javax.swing.JDialog CrockeriesDialog;
    private javax.swing.JButton EB1;
    private javax.swing.JButton EB2;
    private javax.swing.JTextField ENTERname;
    private javax.swing.JTable ET;
    private javax.swing.JRadioButton ElRAButton;
    private javax.swing.JDialog ElectronicsDialog;
    private javax.swing.JButton FB1;
    private javax.swing.JButton FB2;
    private javax.swing.JTable FT;
    private javax.swing.JRadioButton FuRAButton;
    private javax.swing.JDialog FurnituresDialog;
    private javax.swing.JButton GB1;
    private javax.swing.JButton GB2;
    private javax.swing.JTable GT;
    private javax.swing.JRadioButton GaRAButton;
    private javax.swing.JDialog GarmentsDialog;
    private javax.swing.JLabel ID;
    private javax.swing.JTable ItemTable;
    private javax.swing.JDialog Itempurchase;
    private javax.swing.JDialog OptionsDialog;
    private javax.swing.JButton SB1;
    private javax.swing.JButton SB2;
    private javax.swing.JTable ST;
    private javax.swing.JRadioButton SpRAButton;
    private javax.swing.JDialog SportsDialog;
    private javax.swing.JDialog TransactionDialog;
    private javax.swing.JButton TransactionID;
    private javax.swing.JButton VB1;
    private javax.swing.JButton VB2;
    private javax.swing.JTable VT;
    private javax.swing.JRadioButton VeRAButton;
    private javax.swing.JDialog VegetablesDialog;
    private javax.swing.JTextArea cm;
    private javax.swing.JTextField ct1;
    private javax.swing.JTextField ct2;
    private javax.swing.JTextField et1;
    private javax.swing.JTextField et2;
    private javax.swing.JTextField ft1;
    private javax.swing.JTextField ft2;
    private javax.swing.JTextField gt1;
    private javax.swing.JTextField gt2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextField st1;
    private javax.swing.JTextField st2;
    private javax.swing.JTextField vt1;
    private javax.swing.JTextField vt2;
    // End of variables declaration//GEN-END:variables

}
